import {
  AddToCart,
  CarouselPage,
  ContactUs,
  CreateAccount,
  MobileNavigation,
  MusicEvent,
  ProfileCard,
  ChaiRecipe,
  PasswordGenerator,
  HotelBooking,
  SignUp,
  RestaurantReservation,
  TaskBoard,
  ShoppingList,
  Notifications,
  FurFriends,
  ArticleSlider,
  ImagesPreview,
  PhotoUpload,
} from "./solutions";

export const challenges = [
  { day: 1, title: "Profile Card", solution: ProfileCard },
  { day: 2, title: "Add To Bag", solution: AddToCart },
  { day: 3, title: "Mobile Navigation", solution: MobileNavigation },
  { day: 4, title: "Contact Us", solution: ContactUs },
  { day: 5, title: "Recipe", solution: ChaiRecipe },
  { day: 6, title: "Image Carousel", solution: CarouselPage },
  { day: 7, title: "Create Account", solution: CreateAccount },
  { day: 8, title: "Music events", solution: MusicEvent },
  { day: 9, title: "Password Generator", solution: PasswordGenerator },
  { day: 10, title: "Sign Up Page", solution: SignUp },
  { day: 11, title: "Hotel Booking", solution: HotelBooking },
  { day: 12, title: "Restaurant Reservation", solution: RestaurantReservation },
  { day: 13, title: "Task Board", solution: TaskBoard },
  { day: 14, title: "Shopping List", solution: ShoppingList },
  { day: 15, title: "Notification", solution: Notifications },
  { day: 16, title: "FurEver Friends", solution: FurFriends },
  { day: 17, title: "Minion Thoughts", solution: ArticleSlider },
  { day: 18, title: "Images Preview", solution: ImagesPreview },
  { day: 19, title: "Photo Upload", solution: PhotoUpload },
];
