import {
  AddToCart,
  CarouselPage,
  ContactUs,
  CreateAccount,
  MobileNavigation,
  MusicEvent,
  ProfileCard,
  ChaiRecipe,
  PasswordGenerator,
  HotelBooking,
  SignUp,
  RestaurantReservation,
  TaskBoard,
  ShoppingList,
  Notifications,
  FurFriends,
  ArticleSlider,
  ImagesPreview,
  PhotoUpload,
  CardWallet,
  PricingPlan,
  Messages,
  Homepage,
  MovieTickets,
  MeetingSchedule,
  JobBoard,
  LeaderBoard,
  Playlist,
  VideoPlayer,
  Invoices,
  Dashboard,
  Newsletter,
  BrandVisualizer,
  UserProfile,
  RateUs,
  SleepApp,
  ExploreFlights,
  MusicFestival,
  QRCodeScanner,
  FAQ,
  Workspace,
  SettingsAppearance,
} from "./solutions";

export const challenges = [
  { day: 1, title: "Profile Card", solution: ProfileCard },
  { day: 2, title: "Add To Bag", solution: AddToCart },
  { day: 3, title: "Mobile Navigation", solution: MobileNavigation },
  { day: 4, title: "Contact Us", solution: ContactUs },
  { day: 5, title: "Recipe", solution: ChaiRecipe },
  { day: 6, title: "Image Carousel", solution: CarouselPage },
  { day: 7, title: "Create Account", solution: CreateAccount },
  { day: 8, title: "Music events", solution: MusicEvent },
  { day: 9, title: "Password Generator", solution: PasswordGenerator },
  { day: 10, title: "Sign Up Page", solution: SignUp },
  { day: 11, title: "Hotel Booking", solution: HotelBooking },
  { day: 12, title: "Restaurant Reservation", solution: RestaurantReservation },
  { day: 13, title: "Task Board", solution: TaskBoard },
  { day: 14, title: "Shopping List", solution: ShoppingList },
  { day: 15, title: "Notification", solution: Notifications },
  { day: 16, title: "FurEver Friends", solution: FurFriends },
  { day: 17, title: "Minion Thoughts", solution: ArticleSlider },
  { day: 18, title: "Images Preview", solution: ImagesPreview },
  { day: 19, title: "Photo Upload", solution: PhotoUpload },
  { day: 20, title: "Card Wallet", solution: CardWallet },
  { day: 21, title: "Pricing Plan", solution: PricingPlan },
  { day: 22, title: "Messages", solution: Messages },
  { day: 23, title: "Homepage", solution: Homepage },
  { day: 24, title: "Movie Tickets", solution: MovieTickets },
  { day: 25, title: "Meeting Scheduler", solution: MeetingSchedule },
  { day: 26, title: "Job Board", solution: JobBoard },
  { day: 27, title: "Leader Board", solution: LeaderBoard },
  { day: 28, title: "Playlist", solution: Playlist },
  { day: 29, title: "Video Player", solution: VideoPlayer },
  { day: 30, title: "Invoices", solution: Invoices },
  { day: 31, title: "Dashboard", solution: Dashboard },
  { day: 32, title: "Newsletter", solution: Newsletter },
  { day: 33, title: "Brand Visualizer", solution: BrandVisualizer },
  { day: 34, title: "User Profile", solution: UserProfile },
  { day: 35, title: "Rate Us", solution: RateUs },
  { day: 36, title: "Sleep App", solution: SleepApp },
  { day: 37, title: "Explore Flights", solution: ExploreFlights },
  { day: 38, title: "Music Festival", solution: MusicFestival },
  { day: 39, title: "QR Code", solution: QRCodeScanner },
  { day: 40, title: "FAQ", solution: FAQ },
  { day: 41, title: "FAQ", solution: Workspace },
  { day: 42, title: "Settings Appearance", solution: SettingsAppearance },
];
